### ISSUE TITLE
使用MSI在WIN11上安装-使用时界面上看不到图片

### ISSUE THREAD

**Issue by alexlausz** [zhongweili/imagenie#3]
在win11上使用msi包安装，打开软件后自动下载了一些文件，然后开始使用，试了三个功能，选择本地图片后界面上都看不到（类似网页上的断链图片）

**Comment by zhongweili** [comment]
感谢反馈，我还没有在 Windows 运行过，近期会借一台 Windows 设备进行集成

**Comment by zhongweili** [comment]
Windows supported in [v0.2.2](https://github.com/zhongweili/imagenie/releases/tag/app-v0.2.2), tested in my win10.
