### ISSUE TITLE
通过imagenie_0.2.0_x64-setup.exe安装后 在win10无法启动

### ISSUE THREAD

**Issue by Leo10086** [zhongweili/imagenie#4]
具体现象是双击没反应

系统版本：Windows 10 家庭版
版本号：22H2

**Comment by zhanghaotian2018** [comment]
+1

**Comment by zhongweili** [comment]
感谢反馈，我还没有在 Windows 运行过，近期会借一台 Windows 设备进行集成

**Comment by zhongweili** [comment]
Windows supported in [v0.2.2](https://github.com/zhongweili/imagenie/releases/tag/app-v0.2.2)
