### ISSUE TITLE
Windows11安装后运行报错 

### ISSUE THREAD

**Issue by cnazev** [zhongweili/imagenie#9]
使用 imagenie_0.2.2_x64-setup.exe 安装的

---------------------------
Windows - 应用程序错误
---------------------------
0x00007FFC7C893020 指令引用了 0x0000000000000000 内存。该内存不能为 read。

要终止程序，请单击“确定”。
---------------------------
确定   
---------------------------

**Comment by zhongweili** [comment]
这个问题较复杂，有多种原因，可能是本地系统环境造成，我这里无法复现。
